<a href="https://colab.research.google.com/github/Manvi1718/Pytorch/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [4]:
data = [[1,2,4],[6,4,8],[6,6,8],[7,9,2]]
x_tensor =torch.tensor(data)

In [5]:
x_tensor

tensor([[1, 2, 4],
        [6, 4, 8],
        [6, 6, 8],
        [7, 9, 2]])

In [7]:
x_tensor.size()   # to calculate dimension

torch.Size([4, 3])

In [10]:
scaler = torch.tensor(5)

In [11]:
scaler

tensor(5)

In [12]:
scaler.item()

5

In [13]:
vector = torch.tensor([5,4])
vector

tensor([5, 4])

* scaler - single number
* vector - 1D array
* matrix - 2D array 
* tensor - ND array

In [15]:
# array of 0s we pass dim in bracket
torch.zeros((4,6))   

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [17]:
# array of 1s we pass dim in bracket
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
torch.rand(6)

tensor([0.8530, 0.4159, 0.7905, 0.1901, 0.0856, 0.4062])

In [19]:
# random values between 0 and 1
torch.rand((4,6))

tensor([[0.9490, 0.4960, 0.7115, 0.9459, 0.8861, 0.3130],
        [0.8553, 0.5754, 0.2079, 0.7128, 0.0306, 0.8553],
        [0.0689, 0.9997, 0.6749, 0.4654, 0.5431, 0.1606],
        [0.5473, 0.8089, 0.5880, 0.4414, 0.1406, 0.7841]])

In [24]:
tensor1 = torch.tensor([2,4,6])

In [25]:
tensor1

tensor([2, 4, 6])

In [26]:
# addition by scaler
tensor1 + 5

tensor([ 7,  9, 11])

In [27]:
#multiplication by scaler
tensor1 * 5

tensor([10, 20, 30])

In [28]:
tensor2 = torch.tensor([1,2,3])

In [29]:
# add of 2 tensor
tensor1+tensor2

tensor([3, 6, 9])

In [30]:
# mul of 2 tensor
tensor1*tensor2   

tensor([ 2,  8, 18])

In [31]:
x = torch.tensor([
    [1,2,3,4],
    [5,4,6,6],
    [1,5,3,7]
])
y = torch.tensor([
    [9,21,13,14],
    [1,7,4,2],
    [1,5,3,7]
])

In [32]:
x+y

tensor([[10, 23, 16, 18],
        [ 6, 11, 10,  8],
        [ 2, 10,  6, 14]])

In [38]:
x*y

tensor([[ 9, 42, 39, 56],
        [ 5, 28, 24, 12],
        [ 1, 25,  9, 49]])

In [36]:
%%time
# matrix multiplication
torch.matmul(x,y.T)

CPU times: user 148 µs, sys: 7 µs, total: 155 µs
Wall time: 160 µs


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [39]:
%%time
# matrix multiplication
x @ y.T

CPU times: user 148 µs, sys: 7 µs, total: 155 µs
Wall time: 160 µs


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [41]:
# matrix multiplication
torch.mm(x,y.T)

tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [42]:
# generate a tensor and we provide a range
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# linspace is used to generate tensor by providing range with number of number need to generate
torch.linspace(1,100,99)

tensor([  1.0000,   2.0102,   3.0204,   4.0306,   5.0408,   6.0510,   7.0612,
          8.0714,   9.0816,  10.0918,  11.1020,  12.1122,  13.1224,  14.1327,
         15.1429,  16.1531,  17.1633,  18.1735,  19.1837,  20.1939,  21.2041,
         22.2143,  23.2245,  24.2347,  25.2449,  26.2551,  27.2653,  28.2755,
         29.2857,  30.2959,  31.3061,  32.3163,  33.3265,  34.3367,  35.3469,
         36.3571,  37.3673,  38.3776,  39.3878,  40.3980,  41.4082,  42.4184,
         43.4286,  44.4388,  45.4490,  46.4592,  47.4694,  48.4796,  49.4898,
         50.5000,  51.5102,  52.5204,  53.5306,  54.5408,  55.5510,  56.5612,
         57.5714,  58.5816,  59.5918,  60.6020,  61.6122,  62.6224,  63.6327,
         64.6429,  65.6531,  66.6633,  67.6735,  68.6837,  69.6939,  70.7041,
         71.7143,  72.7245,  73.7347,  74.7449,  75.7551,  76.7653,  77.7755,
         78.7857,  79.7959,  80.8061,  81.8163,  82.8265,  83.8367,  84.8469,
         85.8571,  86.8673,  87.8775,  88.8878,  89.8980,  90.90

In [51]:
torch.randint(1,10,size=(3,4))

tensor([[2, 5, 7, 2],
        [2, 9, 9, 5],
        [3, 5, 9, 1]])

In [62]:
x =torch.randint(1,100,size=(20,))

In [63]:
x.min()

tensor(1)

In [64]:
x.max()

tensor(96)

In [65]:
x.type(torch.float32).mean()

tensor(53.9000)

In [67]:
# changes the data arrangement
y = x.reshape(4,5)

In [69]:
# original data as it is with different dim
x.view(5,4)

tensor([[14, 61, 48, 89],
        [ 1, 95, 36, 34],
        [93, 68, 70,  5],
        [13, 31, 69, 53],
        [96, 24, 88, 90]])

In [72]:
y

tensor([[14, 61, 48, 89,  1],
        [95, 36, 34, 93, 68],
        [70,  5, 13, 31, 69],
        [53, 96, 24, 88, 90]])

In [73]:
y[0]

tensor([14, 61, 48, 89,  1])

In [74]:
y[:,0]

tensor([14, 95, 70, 53])

In [75]:
y[0:3,0:2]

tensor([[14, 61],
        [95, 36],
        [70,  5]])