<a href="https://colab.research.google.com/github/Manvi1718/Pytorch/blob/main/SimpleANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [16]:
x =np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]])

y = np.array([[1],[1],[0]])

In [17]:
# ACTIVATION FUNCTION 
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [18]:
x.shape

(3, 4)

In [19]:
# input layer neurons will always be equal to the number of columns
inputNeurons = x.shape[1]
# hidden neurons deciding by hit and trial
hiddenNeurons = 4
# output neurons depend upon  number of classes we have in target column
outputNeurons = 1

In [20]:
# weights initilisation and bias initialisation
weightHidden = np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightOutput = np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

In [21]:
#FEEDFORWARD
#step 1 : apply dot product and add bias : f(x)=x.wh + biasHiddden
fx=np.dot(x,weightHidden) +biasHidden

In [22]:
# step 2 : applying activation function 
hiddenLayer = sigmoid(fx)

In [23]:
hiddenLayer

array([[0.74708541, 0.82757192, 0.90146991, 0.88670241],
       [0.8088436 , 0.83071703, 0.92018135, 0.95039193],
       [0.69296689, 0.82921799, 0.80385215, 0.88986814]])

In [24]:
# step 3 : aplly dot product and add bias : f(x) = hiddenLayer.wOutput + biasOutput
fx_=np.dot(hiddenLayer,weightOutput)+biasOutput

In [25]:
outputLayer = sigmoid(fx_)

In [26]:
outputLayer

array([[0.8018867 ],
       [0.81174784],
       [0.78968865]])

In [27]:
def derivativeSigmoid(x):
  return x*(1-x)

In [28]:
#BACKPROPAGATION

#error on output layer
errorOutput = outputLayer-y
#slope on outputlayer - derivative of activation func applied on this layer
slopeOutput = derivativeSigmoid(outputLayer)
# delta = error X slope
deltaOutput = errorOutput * slopeOutput

In [29]:
errorHidden = np.dot(deltaOutput,weightOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [30]:
errorOutput

array([[-0.1981133 ],
       [-0.18825216],
       [ 0.78968865]])

In [31]:
alpha = 0.01
#weight optimisation
weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha
weightHidden = weightHidden - x.T.dot(deltaHidden) * alpha
#bias optimisation
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha 

In [41]:
# weights initilisation and bias initialisation
weightHidden = np.random.uniform(size=(inputNeurons,hiddenNeurons))
biasHidden = np.random.uniform(size=(1,hiddenNeurons))
weightOutput = np.random.uniform(size=(hiddenNeurons,outputNeurons))
biasOutput = np.random.uniform(size=(1,outputNeurons))

alpha = 0.09
epochs = 40000

for i in range(epochs):
  #FEEDFORWARD

  #step 1 : apply dot product and add bias : f(x)=x.wh + biasHiddden
  fx=np.dot(x,weightHidden) +biasHidden
  # step 2 : applying activation function 
  hiddenLayer = sigmoid(fx)
  # step 3 : aplly dot product and add bias : f(x) = hiddenLayer.wOutput + biasOutput
  fx_=np.dot(hiddenLayer,weightOutput)+biasOutput
  # step 4 : applying activation func to output layer
  outputLayer = sigmoid(fx_)

  #BACKPROPAGATION

  #error on output layer
  errorOutput = outputLayer-y
  #slope on outputlayer - derivative of activation func applied on this layer
  slopeOutput = derivativeSigmoid(outputLayer)
  # delta = error X slope
  deltaOutput = errorOutput * slopeOutput
  # error calculation for hidden layer
  errorHidden = np.dot(deltaOutput,weightOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden
  #OPTIMISATION
  #weight optimisation
  weightOutput = weightOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightHidden = weightHidden - x.T.dot(deltaHidden) * alpha
  #bias optimisation
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha 
print(outputLayer)

[[0.99540814]
 [0.99190403]
 [0.01207735]]
