<a href="https://colab.research.google.com/github/Manvi1718/Pytorch/blob/main/TENSOR_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**TENSORS** Fundamentals

###Creating Tensors

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#saclar
scalar = torch.tensor(18)
scalar

tensor(18)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor as int of python
scalar.item()

18

In [ ]:
# Vector
vector = torch.tensor([17,18])
vector

tensor([17, 18])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
matrix = torch.tensor([[1,2],
                       [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[:,1]

tensor([2, 4])

In [ ]:
# TENSOR
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

###Random Tensors


random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numners -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# create random tensor of size(3,4)
# Generates between 0 to 1
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.0890, 0.3977, 0.5881, 0.9771],
         [0.0289, 0.7406, 0.8380, 0.1209],
         [0.8603, 0.1607, 0.8660, 0.8102]],

        [[0.7580, 0.3713, 0.9112, 0.4673],
         [0.1783, 0.0718, 0.7344, 0.6881],
         [0.9757, 0.2428, 0.0824, 0.0550]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size =(224,224,3)) # height , weight and color channel
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
# create a tensor with all zeros
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
# use torch.range() and get depricated message , use torch.arange() instead
# provide a range of i.e. start , stop and sometimes step
one_to_ten = torch.arange(0,10,2 , dtype=torch.float32)
one_to_ten

tensor([0., 2., 4., 6., 8.])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0.])

###Tensor Datatypes

**Note** tensor datatypes is one of the 3 big errors we will run into with pytorch and deep learning :

1) Tensors not right datatype

2) Tnesors not right shape

3) tensors not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.8,5.6,7.0],
                               dtype = None ,
                               device = None , # device of tensor
                               requires_grad = False) # wheter or not to track gradients with this tensor operations
float_32_tensor

tensor([3.8000, 5.6000, 7.0000])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.8008, 5.6016, 7.0000], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([14.4430, 31.3687, 49.0000])

In [ ]:
int_32_tensor = torch.tensor([3,4,5],dtype = torch.long)
int_32_tensor

tensor([3, 4, 5])

In [ ]:
float_32_tensor * int_32_tensor

tensor([11.4000, 22.4000, 35.0000])

###Getting Information from tensors (TENSOR ATTRIBUTES)

1) Tensors not right **datatype** - to get 'dtype' from a tensor use **'tensor.dtype'**

2) Tnesors not right **shape** - to get shape from tensor , can use **'tensor.shape'**

3) tensors not on the right device - to get device of tensor , can use **'tensor.device'**

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0393, 0.9803, 0.5135, 0.8474],
        [0.6579, 0.1995, 0.3888, 0.1707],
        [0.6169, 0.4481, 0.5220, 0.6608]])

In [ ]:
# find out details about tensor
print(some_tensor)
print(f"datatype of tensor :{some_tensor.dtype}")
print(f"M1 shape of tensor :{some_tensor.shape}")
print(f"M2 shape of tensor :{some_tensor.size()}")
print(f"device of tensor :{some_tensor.device}")



tensor([[0.0393, 0.9803, 0.5135, 0.8474],
        [0.6579, 0.1995, 0.3888, 0.1707],
        [0.6169, 0.4481, 0.5220, 0.6608]])
datatype of tensor :torch.float32
M1 shape of tensor :torch.Size([3, 4])
M2 shape of tensor :torch.Size([3, 4])
device of tensor :cpu


###Manipulating Tensors (Tensor Operations)

Tensor operation includes:

* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix - Multiplication


In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor = tensor * 10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor/10

tensor([1., 2., 3.])

In [ ]:
tensor-1

tensor([ 9, 19, 29])

In [ ]:
# torch innuilt function

torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,2)

tensor([12, 22, 32])

In [ ]:
torch.subtract(tensor,2)

tensor([ 8, 18, 28])

In [ ]:
torch.divide(tensor,10)

tensor([1., 2., 3.])

###Matrix Multiplication

2 main ways of performing multplication in neural networks and deep learning :

1)element-wise multiplication

2)matrix multiplication(dot procuct)

In [ ]:
# element wise multiplication
print(tensor, "*",tensor)
print(f"equals : {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
equals : tensor([100, 400, 900])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 1.45 ms, sys: 72 µs, total: 1.52 ms
Wall time: 1.53 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 58 µs, sys: 10 µs, total: 68 µs
Wall time: 73 µs


tensor(1400)

##Finding min , max , sum , mean , etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# find min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
# find max
torch.max(x) ,x.max()

(tensor(90), tensor(90))

In [ ]:
# find mean
# NOTE  torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the position in tensor that has minimum value with argmin() -> returns index postion of target tensor with minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# find the position in tensor that has maxmimum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

##Reshaping , stacking , squeezing and unsqueezing

* Reshaping - reshapes and input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memeory as the original tensor
* Stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with dimensions permuted(swaped) in a certain way

In [ ]:
# create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x ( because view of tensor shares same memory as the original)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stack = torch.stack([x,x,x,x],dim=0) # dim 0 = top of each other || # dim 1 = side by side
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_squeeze= x_reshaped.squeeze()

In [ ]:
# x.unsqueeze() adds a single dimension to a target tensor at a specific dim(dimension)
#1
x_unsqueeze=x_squeeze.unsqueeze(dim=0)
print(x_unsqueeze)
print(x_unsqueeze.shape)
#2
x_unsqueeze=x_squeeze.unsqueeze(dim=1)
print(x_unsqueeze)
print(x_unsqueeze.shape)


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified way
x_original = torch.rand(size=(224,223,3)) #[height,width , color_channels]
print(x_original.shape)
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2 , 2->0
print(x_permuted.shape)

torch.Size([224, 223, 3])
torch.Size([3, 224, 223])


##Indexing(selecting data from tensors)

Indexing with PyTorch is similar to Indexing with Numpy

In [ ]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

5

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

##Pytorch tensors and Numpy

numpy is a popular scientific python numerical computing library

and because of this ,Pytorch has functionality to interact with it

* Data in Numpy , want in PyTorch tensor ->` torch.from_numpy(ndarray)`

* Pytorch -> Numpy ->`torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
array = array+1
array , tensor
# changing the value of array does not change the value of tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor , what happens to numpy
tensor = tensor+1
tensor,numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility( trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again->again->again...`

to  reduce the randomness in a neural networks and PyTorch comes the concept of **random seed**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch

# create two random tensors
random_tensor_A= torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6558, 0.7571, 0.1343, 0.9830],
        [0.6787, 0.2169, 0.6186, 0.0806],
        [0.9087, 0.6900, 0.9858, 0.4696]])
tensor([[0.0244, 0.9783, 0.5180, 0.2703],
        [0.4237, 0.4988, 0.8049, 0.8587],
        [0.6165, 0.0182, 0.4852, 0.2673]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and PyTorch objects on the GPUs (making faster computations)

Getting a GPU

* Easiest - use a google colab for a free GPU (Options to upgrade as well)

* Use your own GPU - takes a setup and requires investment of purchasing

* use clod computing - GCP,AWS,Azure,these services allow you to rent computers on cloud and acces them





### check for GPU acces

In [1]:
import torch
torch.cuda.is_available()

True

For PyTorch since its capable of running on the GPU or CPU , its best practice to setup device agnostic code

In [2]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# count number of devices
torch.cuda.device_count()

1

###Putting tensors (and models) on GPU

the reason we want our tensors/ models on GPU is because using a GPU results in Faster Compulations

In [4]:
# create a tensor(default on CPU)
tensor = torch.tensor([1,2,3] , device="cpu")

# tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# move tensor to GPU (if available)
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

###Moving tensors back to GPU

In [6]:
# if tensor is on GPU , cant transform it into numpy
tensor_on_GPU.numpy()

TypeError: ignored

In [7]:
# to fix the GPU tensor with numpy , we can first set it to cpu
tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

##Exercises

2)Create a random tensor with shape (7, 7).

In [9]:
import torch
x = torch.rand(7,7)
x

tensor([[0.7579, 0.9100, 0.2020, 0.6802, 0.3940, 0.8331, 0.7387],
        [0.7154, 0.5089, 0.6271, 0.5532, 0.4681, 0.5562, 0.3756],
        [0.9684, 0.4249, 0.8279, 0.5606, 0.1231, 0.6517, 0.0529],
        [0.9913, 0.4059, 0.4799, 0.8208, 0.4787, 0.7804, 0.7897],
        [0.3248, 0.2580, 0.6236, 0.7491, 0.1521, 0.2513, 0.0596],
        [0.4709, 0.8503, 0.1862, 0.5968, 0.4065, 0.3190, 0.8672],
        [0.7000, 0.3037, 0.4665, 0.8574, 0.0709, 0.9646, 0.7507]])

3)Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [12]:
y = torch.rand(1,7)
z = torch.matmul(x,y.T)
z

tensor([[1.4596],
        [1.1989],
        [1.0961],
        [1.7189],
        [0.6956],
        [1.2499],
        [1.5533]])

4)Set the random seed to 0 and do exercises 2 & 3 over again.

In [17]:
Random_seed= 0
torch.manual_seed(Random_seed)
x = torch.rand(7,7)
torch.manual_seed(Random_seed)
y = torch.rand(1,7)
z = torch.matmul(x,y.T)
z


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5)Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [21]:
torch.manual_seed(1234)
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)
x = torch.rand(7,7).cuda()
print(f"x is {x}")
y = torch.rand(1,7).cuda()
print(f"y is {y}")
z = torch.matmul(x,y.T)
print(f" z is {z}")


x is tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]],
       device='cuda:0')
y is tensor([[0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993]],
       device='cuda:0')
 z is tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]], device='cuda:0')


6)Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [25]:
device = "cuda" if torch.cuda.is_available else "cpu"
torch.manual_seed(1234)
x = torch.rand(2,3)
x_gpu = x.to(device)
torch.manual_seed(1234)
y = torch.rand(2,3)
y_gpu= y.to(device)
x_gpu , y_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

7)Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [27]:
z = torch.matmul(x_gpu,y_gpu.T)
print(z)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


8)Find the maximum and minimum values of the output of 7

In [32]:
z.max() , torch.max(z)

(tensor(0.6287, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [33]:
z.min() , torch.min(z)

(tensor(0.2161, device='cuda:0'), tensor(0.2161, device='cuda:0'))

9)Find the maximum and minimum index values of the output of 7.

In [37]:
z.argmax() , torch.argmax(z)

(tensor(3, device='cuda:0'), tensor(3, device='cuda:0'))

In [38]:
z.argmin() , torch.argmin(z)

(tensor(1, device='cuda:0'), tensor(1, device='cuda:0'))

10)Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [41]:
torch.manual_seed(7)
x = torch.rand(1,1,1,10)
print(f"first tensor is {x}")
print(f"shape of tensor is {x.shape}")
x_squeeze = x.squeeze()
print(x_squeeze.shape)

first tensor is tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
shape of tensor is torch.Size([1, 1, 1, 10])
torch.Size([10])
